package server.objects;

import java.util.Map;
import java.util.HashMap;
import java.util.Collections;
import server.objects.instantiables.*;


/*** THIS CLASS IS AUTO GENERATED BY compile_server.py. CHANGES TO THIS WILL NOT BE SAVED. ***/
// This class contains a map from the strings of each class to the objects they represent.
// This allows us to get instantiable classes by their strings.
public class Instantiables {
	public static final Map<String, Object> instantiables;
	static {
		Map<String, Object> map = new HashMap<String, Object>();
		map.put("item", new Item());
		map.put("block", new Block());
		map.put("mob", new Mob());
		instantiables = Collections.unmodifiableMap(map);
	}
}
