package server.actions;

/*** THIS CLASS IS AUTO GENERATED BY compile_server.py. CHANGES TO THIS WILL NOT BE SAVED. ***/
// This class contains all the actions in the actions folder. This allows us to easily iterate over every action.
public class Actions {
	// array containing all the actions.
	public static final Action[] actions = new Action[] {
		new ShowStats(),
		new Upgrade(),
		new CreateAccount(),
		new Run(),
		new ShortCut(),
		new Display(),
		new Attack(),
		new Move(),
		new Login(),
		new ShowXP(),
		new Give(),
		new Help(),
		new DescribeItem(),
		new Mark(),
		new ShowInventory(),
		new Eat(),
		new ShowMap(),
	};
}
